apiVersion: v2
name: counter-service
description: A Helm chart for the counter-service application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: redis
    version: ">=23.0.0 <25.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kube-prometheus-stack
    version: ">=59.0.0 <60.0.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled
    alias: prometheus
  - name: secrets-store-csi-driver
    version: ">=1.3.0 <2.0.0"
    repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    condition: secrets-store-csi-driver.enabled
