apiVersion: v2
name: counter-service
description: A Helm chart for the counter-service application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: redis
    version: ">=23.0.0 <25.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
