apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: redis-secret-provider
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  # This service account needs permissions to get the secret
  serviceAccountName: {{ .Values.serviceAccount.name }}
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-2:630943284793:secret:prod/redis/password-owHTAL"
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: password
  secretObjects:
  - secretName: redis-secret
    type: Opaque
    data:
    - key: password
      objectName: password
