{{- if .Values.appSecrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.appSecrets.providerName }}
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.appSecrets.secretArn | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: "redis-password"

  # This section instructs the driver to also create a standard Kubernetes Secret
  # This is useful for applications that can't read from mounted files (like the Bitnami Redis chart)
  secretObjects:
    - secretName: {{ .Values.appSecrets.k8sSecretName }}
      type: Opaque
      data:
        - objectName: "redis-password"
          key: "password"
{{- end }}
