apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-admin-secrets-provider
  namespace: monitoring
spec:
  provider: aws
  # Tell the CSI driver which Service Account to use for fetching the secret
  serviceAccountName: "grafana"
  parameters:
    objects: |
      - objectName: "arn:aws:iam::630943284793:secret:prod/grafana/admin-GAfsHU"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: username
          - path: "password"
            objectAlias: password
  secretObjects:
  - secretName: grafana-admin-credentials
    type: Opaque
    data:
    - key: username
      objectName: username
    - key: password
      objectName: password
