apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: redis-secret-provider
  namespace: prod
spec:
  provider: aws
  serviceAccountName: counter-service # The SA that will use this secret
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-2:630943284793:secret:prod/redis/password-owHTAL"
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: password
  secretObjects:
  - secretName: redis-secret
    type: Opaque
    data:
    - key: password
      objectName: password
