apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: redis-secret-provider
  namespace: prod
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-2:630943284793:secret:prod/redis/password-owHTAL"
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: password
        # --- NEW: Mount the secret as a file ---
        path: "password" # This will create /mnt/secrets/redis-password
        # --- END NEW ---
  secretObjects:
  - secretName: redis-secret
    type: Opaque
    data:
    - key: password
      objectName: password
